version: '3.3'
services:
  postgis:
    container_name: touraxis_postgis_container
    image: postgis/postgis
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
  pgadmin4:
    container_name: touraxis_pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
