on: ["push", "pull_request"]

name: Test

jobs:
  test-and-push-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install
        run: npm i
      - name: Test and Cov
        run: npm run test:cov

      ### this step!
      - name: Cov Badge And Publish
        uses: nolleh/jest-badge-deploy-action@latest
